# backend/agents/gst_invoice_generator.py
"""Auto-generate GST-compliant invoices from transaction data."""
from jinja2 import Template
from datetime import date
from pathlib import Path
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select


class GSTInvoiceGenerator:
    def __init__(self, db: AsyncSession):
        self.db = db
    
    async def generate(self, user_id: str, transaction_id: str) -> dict:
        from models.transaction import Transaction
        from models.user import User
        from services.storage import StorageService
        from datetime import date
        
        # Fetch transaction and user
        tx_result = await self.db.execute(
            select(Transaction).where(Transaction.id == transaction_id, Transaction.user_id == user_id)
        )
        tx = tx_result.scalar_one_or_none()
        if not tx:
            raise ValueError(f"Transaction {transaction_id} not found")
        
        user_result = await self.db.execute(select(User).where(User.id == user_id))
        user = user_result.scalar_one_or_none()
        if not user:
            raise ValueError(f"User {user_id} not found")
        
        # Build invoice data
        subtotal = tx.amount / 1.18  # Back-calculate pre-GST amount
        cgst = sgst = (tx.amount - subtotal) / 2
        
        invoice_number = f"INV-{user_id[:6].upper()}-{date.today().strftime('%Y%m%d')}-{transaction_id[:4].upper()}"
        
        # HTML Template
        GST_INVOICE_TEMPLATE = """<!DOCTYPE html>
<html><head><meta charset="UTF-8">
<style>
  body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; }
  .header { display: flex; justify-content: space-between; border-bottom: 2px solid #333; padding-bottom: 20px; }
  .invoice-title { font-size: 28px; font-weight: 900; color: #1a1a2e; }
  .gst-badge { background: #16a34a; color: white; padding: 4px 12px; border-radius: 4px; font-size: 12px; }
  table { width: 100%; border-collapse: collapse; margin: 20px 0; }
  th { background: #1a1a2e; color: white; padding: 10px; text-align: left; }
  td { padding: 8px 10px; border-bottom: 1px solid #e2e8f0; }
  .total-row { font-weight: 700; background: #f0fdf4; }
  .footer { margin-top: 40px; font-size: 12px; color: #64748b; }
</style>
</head>
<body>
<div class="header">
  <div>
    <div class="invoice-title">TAX INVOICE</div>
    <span class="gst-badge">GST Compliant</span>
    <p style="margin-top:10px; color:#64748b">Invoice #: {{ invoice_number }}</p>
    <p style="color:#64748b">Date: {{ invoice_date }}</p>
  </div>
  <div style="text-align:right">
    <div style="font-size:20px; font-weight:700">{{ seller_name }}</div>
    <p>{{ seller_business }}</p>
    <p>{{ seller_location }}</p>
    {% if seller_gstin %}<p><strong>GSTIN:</strong> {{ seller_gstin }}</p>{% endif %}
  </div>
</div>

<div style="margin:20px 0">
  <strong>Bill To:</strong> {{ buyer_name or 'Walk-in Customer' }}<br>
  {% if buyer_phone %}<span>Phone: {{ buyer_phone }}</span>{% endif %}
</div>

<table>
  <tr><th>Description</th><th>Qty</th><th>Rate (₹)</th><th>GST%</th><th>Amount (₹)</th></tr>
  {% for item in items %}
  <tr>
    <td>{{ item.description }}</td>
    <td>{{ item.qty or 1 }}</td>
    <td>{{ "{:,.2f}".format(item.rate) }}</td>
    <td>{{ item.gst_pct or 18 }}%</td>
    <td>{{ "{:,.2f}".format(item.amount) }}</td>
  </tr>
  {% endfor %}
  <tr class="total-row">
    <td colspan="4">Subtotal</td><td>₹{{ "{:,.2f}".format(subtotal) }}</td>
  </tr>
  <tr>
    <td colspan="4">CGST (9%)</td><td>₹{{ "{:,.2f}".format(cgst) }}</td>
  </tr>
  <tr>
    <td colspan="4">SGST (9%)</td><td>₹{{ "{:,.2f}".format(sgst) }}</td>
  </tr>
  <tr class="total-row">
    <td colspan="4"><strong>Total Amount</strong></td>
    <td><strong>₹{{ "{:,.2f}".format(total) }}</strong></td>
  </tr>
</table>

<div style="margin-top:20px; padding:15px; background:#f8fafc; border-radius:8px">
  <strong>Amount in Words:</strong> {{ amount_in_words }}
</div>

<div class="footer">
  <p>Generated by ArthAI™ — India's Financial Intelligence Layer</p>
  <p>This is a computer-generated invoice and does not require a physical signature.</p>
</div>
</body></html>"""

        data = {
            "invoice_number": invoice_number,
            "invoice_date": date.today().strftime("%d %B %Y"),
            "seller_name": user.name or "Business Owner",
            "seller_business": user.business_type or "Business",
            "seller_location": user.business_location or "India",
            "seller_gstin": None,  # To be added when user provides GSTIN
            "buyer_name": tx.counterparty,
            "buyer_phone": None,
            "items": [{"description": tx.description or "Services", "qty": 1, "rate": subtotal, "gst_pct": 18, "amount": subtotal}],
            "subtotal": subtotal,
            "cgst": cgst,
            "sgst": sgst,
            "total": tx.amount,
            "amount_in_words": self._num_to_words(tx.amount),
        }
        
        html_content = Template(GST_INVOICE_TEMPLATE).render(**data)
        
        try:
            from weasyprint import HTML as WeasyHTML
            pdf_bytes = WeasyHTML(string=html_content).write_pdf()
            file_ext, content_type = "pdf", "application/pdf"
        except Exception:
            pdf_bytes = html_content.encode("utf-8")
            file_ext, content_type = "html", "text/html"
        
        storage = StorageService()
        file_key = f"invoices/{user_id}/{invoice_number}.{file_ext}"
        download_url = await storage.upload_file(pdf_bytes, file_key, content_type)
        
        return {"invoice_number": invoice_number, "download_url": download_url}
    
    def _num_to_words(self, amount: float) -> str:
        """Convert amount to Indian words (simplified)."""
        rupees = int(amount)
        if rupees >= 100000:
            return f"Rupees {rupees / 100000:.1f} Lakhs Only"
        if rupees >= 1000:
            return f"Rupees {rupees / 1000:.1f} Thousand Only"
        return f"Rupees {rupees} Only"
